# /Workflow-CI/.github/workflows/ci_workflow.yml

name: CI Model Retraining and Artifact Upload (Skilled)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # 1. Setup Python Environment
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
        
    # 2. Install MLflow CLI (untuk menjalankan project)
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0
        
    # 3. Jalankan MLflow Project (Model Retraining)
    - name: Run MLflow Project and Retrain Model
      run: |
        # Pindah ke direktori MLProject
        cd MLProject
        # Jalankan project yang akan melatih model dan menyimpan artefak lokal
        mlflow run . --experiment-name "CI_Retraining_Run"
        
    # 4. Upload Artifacts ke GitHub (WAJIB Kriteria 3 Skilled)
    - name: Upload MLflow Artifacts to Repository
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        # MLflow menyimpan tracking di mlruns. Kita hanya perlu artefak model
        path: MLProject/mlruns/